### ISSUE TITLE
ESM (mjs) & cjs build to support imports from ESM

### ISSUE THREAD

**Issue by btakita** [lukeed/webpack-format-messages#8]
Hello again, please excuse the form post, I mainly need the issue number:

Following the technique presented in https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html, a library can have both cjs & mjs outputs. I'll submit a PR using this technique but am not attached to using Typescript, as long as there is an mjs & cjs build.

**Comment by lukeed** [comment]
3.0 is now available with native ESM support

**Comment by btakita** [comment]
Thank you!

**Comment by jsg2021** [comment]
The import map points "require" to index.js but that file is still using esm import for kleur/colors... this doesn't work for code using require path. 

I was able to get 3.0 working with my existing webpack by changing my `require()` to `await import()`... which was fine for me, because I already had an async function around my config... those using traditional cjs webpack configs will get hit by this.

**Comment by lukeed** [comment]
Oh shoot, thanks

**Comment by lukeed** [comment]
Fixed in 3.0.1
